---
title: "Adegenet Analyses"
author: "Eric Crandall"
date: "September 9, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("hierfstat")
library("adegenet")
library("pegas")
```


## Read in some of the simulated msat data and play with it.


```{r, echo=FALSE}
# see http://adegenet.r-forge.r-project.org/files/tutorial-basics.pdf

msat<-read.genepop("./pareto2_snps/pareto2_2.gen",ncode=3L)

print("overall FST")
fstat(msat)
print("locus-wise FST")
Fst(as.loci(msat))
print("pairwise FST")
pfstmsat<-pairwise.fst(msat)
pfstmsat

print("PCA")
#msatscaled<-scaleGen(msat)
pca1 <- dudi.pca(msat,cent=FALSE,scale=TRUE,scannf=FALSE,nf=3)
#barplot(pca1$eig[1:50],main="PCA eigenvalues", col=heat.colors(50))
#s.label(pca1$li)
#add.scatter.eig(pca1$eig[1:20], 3,1,2)
#s.class(pca1$li, pop(msat))
#add.scatter.eig(pca1$eig[1:20], 3,1,2)
col<-funky(15)
s.class(pca1$li, pop(msat),xax=1,yax=2, col=transp(col,.6), axesell=FALSE,
        cstar=0, cpoint=3, grid=TRUE)
        
        
print("Isolation-By-Distance")
msatpop<-genind2genpop(msat)

#read in locations on the lattice
latdists<-read.table("distances.txt")
latdists<-dist(latdists)

ibd<-mantel.randtest(pfstmsat,latdists)
ibd
plot(latdists, pfstmsat)
abline(lm(pfstmsat~latdists))
plot(ibd)
        
```
